pipeline{
	agent{ label 'master'}

		stages{
			stage('test'){
				steps{
					echo "mvn clean compile test"
				}
			}

			stage('build application'){
				steps{
					dir("."){
						echo "mvn -f pom.xml clean install -Dmaven.test.skip-true"
						echo "tree"
					}
				}
			}

			stage('nexus'){
				steps{
					script{
						dir("."){
							def pom = readMavenPom file: "pom.xml";
						
							dir("target"){
								nexusArtifactUploader(
									nexusVersion: 'nexus3',
									protocol: 'http',
									nexusUrl: 'localhost:8081',
									groupId: 'org.springframework.data.examples',
									version: pom.version,
									repository: 'ProyectoPractica2',
									credentialsId: 'nexuscrecial',
									artifacts: [
										[artifactId: pom.artifactId,
										classifier: '',
										file: 'spring-data-web-example-2.0.0.BUILD-SNAPSHOT.jar',
										type: pom.packaging]
									]
								)
							}
						}	
					}
				}
			}
			
		}
}







