pipeline{
	agent{ label 'master'}

		stages{
			stage('test'){
				steps{
					bat "mvn clean compile test"
				}
			}
			stage('nexus'){
				steps{
					script{
						dir(""){
							def pom = readMavenPom file: "pom.xml";
						
							dir("target"){
								nexusArtifactUploader(
									nexusVersion: 'nexus3',
									protocol: 'http',
									nexusUrl: 'localhost:8081',
									groupId: pom.groupId,
									version: pom.version,
									repository: 'ProyectoPractica2',
									credentialsId: 'nexuscredentiales',
									artifacts: [
										[artifactId: pom.artifactId,
										classifier: '',
										file: '',
										type: pom.packaging]
									]
								)
							}
						}	
					}
				}
			}
			
		}
}







